AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  over4kmain:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::493890830578:role/service-role/simple-microservice'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
      Environment:
        Variables:
          DEBUG: lambda
